apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors
  labels:
    apps.tanzu.vmware.com/workload-type: web
spec:
  source:
    git:
      url: https://github.com/tsalm-pivotal/tap-demos-w01-s002.git
      ref:
        branch: main
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: rmq-1

